project_id = "yhnmadrqghlmeknwujii"

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.og-image]
verify_jwt = false

[functions.delete-account]
verify_jwt = false
